import 'dart:io';

/// Code generator for OrtApi indices from onnxruntime_c_api.h.
/// Specification: Appendix A in VeneraX AI Translation Implementation Plan.
void main(List<String> args) {
  var headerPath = '.cache/ort/headers/onnxruntime_c_api.h';
  var outputPath = 'lib/foundation/image_translation/ort_api_indices.g.dart';

  for (var i = 0; i < args.length; i++) {
    if (args[i] == '--header' && i + 1 < args.length) {
      headerPath = args[i + 1];
      i++;
    } else if (args[i] == '--output' && i + 1 < args.length) {
      outputPath = args[i + 1];
      i++;
    }
  }

  final headerFile = File(headerPath);
  if (!headerFile.existsSync()) {
    stderr.writeln('Error: Header file not found at: $headerPath');
    exit(1);
  }

  final content = headerFile.readAsStringSync();
  final structMatch = RegExp(r'struct OrtApi \{(.*?)\};', dotAll: true).firstMatch(content);
  if (structMatch == null) {
    stderr.writeln('Error: struct OrtApi not found in header: $headerPath');
    exit(1);
  }

  final body = structMatch.group(1)!;
  final lines = body.split('\n');
  final entries = <String>[];

  final p1 = RegExp(r'\(\s*ORT_API_CALL\s*\*\s*([A-Za-z0-9_]+)\s*\)');
  final p2 = RegExp(r'ORT_API2_STATUS\s*\(\s*([A-Za-z0-9_]+)\s*,');
  final p3 = RegExp(r'ORT_CLASS_RELEASE\s*\(\s*([A-Za-z0-9_]+)\s*\)');

  for (final line in lines) {
    final m1 = p1.firstMatch(line);
    if (m1 != null) {
      entries.add(m1.group(1)!);
      continue;
    }
    final m2 = p2.firstMatch(line);
    if (m2 != null) {
      entries.add(m2.group(1)!);
      continue;
    }
    final m3 = p3.firstMatch(line);
    if (m3 != null) {
      entries.add('Release${m3.group(1)!}');
      continue;
    }
  }

  print('Parsed ${entries.length} OrtApi member functions.');

  // Self-checks from Appendix A
  final requiredChecks = <String, int>{
    'CreateStatus': 0,
    'GetErrorCode': 1,
    'GetErrorMessage': 2,
    'CreateEnv': 3,
    'CreateSession': 7,
    'Run': 9,
    'CreateSessionOptions': 10,
    'SetIntraOpNumThreads': 24,
    'CreateTensorWithDataAsOrtValue': 49,
    'ReleaseStatus': 93,
    'ReleaseSession': 95,
    'ReleaseValue': 96,
    'ReleaseSessionOptions': 100,
  };

  for (final entry in requiredChecks.entries) {
    final actual = entries.indexOf(entry.key);
    if (actual != entry.value) {
      stderr.writeln(
        'Self-check failed: ${entry.key} expected index ${entry.value}, got $actual',
      );
      exit(1);
    }
  }
  print('All required self-checks passed.');

  String toCamelCase(String pascal) {
    if (pascal.isEmpty) return pascal;
    if (pascal.startsWith('_')) pascal = pascal.substring(1);
    return pascal[0].toLowerCase() + pascal.substring(1);
  }

  final sb = StringBuffer();
  sb.writeln("// GENERATED by tool/gen_ort_api.dart —— 不要手改；重新生成：dart run tool/gen_ort_api.dart --header <path>");
  sb.writeln("// ignore_for_file: constant_identifier_names");
  sb.writeln("part of 'ort_ffi.dart';");
  sb.writeln();
  sb.writeln("/// Stable table indices in struct OrtApi from onnxruntime_c_api.h.");
  sb.writeln("abstract final class OrtApiIdx {");

  for (var idx = 0; idx < entries.length; idx++) {
    final originalName = entries[idx];
    final camelName = toCamelCase(originalName);
    sb.writeln("  /// OrtApi::$originalName ($idx)");
    sb.writeln("  static const int $camelName = $idx;");
  }

  sb.writeln("}");

  final outFile = File(outputPath);
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(sb.toString());
  print('Wrote generated indices to $outputPath');
}
