// GENERATED by tool/gen_ort_api.dart —— 不要手改；重新生成：dart run tool/gen_ort_api.dart --header <path>
// ignore_for_file: constant_identifier_names
part of 'ort_ffi.dart';

/// Stable table indices in struct OrtApi from onnxruntime_c_api.h.
abstract final class OrtApiIdx {
  /// OrtApi::CreateStatus (0)
  static const int createStatus = 0;
  /// OrtApi::GetErrorCode (1)
  static const int getErrorCode = 1;
  /// OrtApi::GetErrorMessage (2)
  static const int getErrorMessage = 2;
  /// OrtApi::CreateEnv (3)
  static const int createEnv = 3;
  /// OrtApi::CreateEnvWithCustomLogger (4)
  static const int createEnvWithCustomLogger = 4;
  /// OrtApi::EnableTelemetryEvents (5)
  static const int enableTelemetryEvents = 5;
  /// OrtApi::DisableTelemetryEvents (6)
  static const int disableTelemetryEvents = 6;
  /// OrtApi::CreateSession (7)
  static const int createSession = 7;
  /// OrtApi::CreateSessionFromArray (8)
  static const int createSessionFromArray = 8;
  /// OrtApi::Run (9)
  static const int run = 9;
  /// OrtApi::CreateSessionOptions (10)
  static const int createSessionOptions = 10;
  /// OrtApi::SetOptimizedModelFilePath (11)
  static const int setOptimizedModelFilePath = 11;
  /// OrtApi::CloneSessionOptions (12)
  static const int cloneSessionOptions = 12;
  /// OrtApi::SetSessionExecutionMode (13)
  static const int setSessionExecutionMode = 13;
  /// OrtApi::EnableProfiling (14)
  static const int enableProfiling = 14;
  /// OrtApi::DisableProfiling (15)
  static const int disableProfiling = 15;
  /// OrtApi::EnableMemPattern (16)
  static const int enableMemPattern = 16;
  /// OrtApi::DisableMemPattern (17)
  static const int disableMemPattern = 17;
  /// OrtApi::EnableCpuMemArena (18)
  static const int enableCpuMemArena = 18;
  /// OrtApi::DisableCpuMemArena (19)
  static const int disableCpuMemArena = 19;
  /// OrtApi::SetSessionLogId (20)
  static const int setSessionLogId = 20;
  /// OrtApi::SetSessionLogVerbosityLevel (21)
  static const int setSessionLogVerbosityLevel = 21;
  /// OrtApi::SetSessionLogSeverityLevel (22)
  static const int setSessionLogSeverityLevel = 22;
  /// OrtApi::SetSessionGraphOptimizationLevel (23)
  static const int setSessionGraphOptimizationLevel = 23;
  /// OrtApi::SetIntraOpNumThreads (24)
  static const int setIntraOpNumThreads = 24;
  /// OrtApi::SetInterOpNumThreads (25)
  static const int setInterOpNumThreads = 25;
  /// OrtApi::CreateCustomOpDomain (26)
  static const int createCustomOpDomain = 26;
  /// OrtApi::CustomOpDomain_Add (27)
  static const int customOpDomain_Add = 27;
  /// OrtApi::AddCustomOpDomain (28)
  static const int addCustomOpDomain = 28;
  /// OrtApi::RegisterCustomOpsLibrary (29)
  static const int registerCustomOpsLibrary = 29;
  /// OrtApi::SessionGetInputCount (30)
  static const int sessionGetInputCount = 30;
  /// OrtApi::SessionGetOutputCount (31)
  static const int sessionGetOutputCount = 31;
  /// OrtApi::SessionGetOverridableInitializerCount (32)
  static const int sessionGetOverridableInitializerCount = 32;
  /// OrtApi::SessionGetInputTypeInfo (33)
  static const int sessionGetInputTypeInfo = 33;
  /// OrtApi::SessionGetOutputTypeInfo (34)
  static const int sessionGetOutputTypeInfo = 34;
  /// OrtApi::SessionGetOverridableInitializerTypeInfo (35)
  static const int sessionGetOverridableInitializerTypeInfo = 35;
  /// OrtApi::SessionGetInputName (36)
  static const int sessionGetInputName = 36;
  /// OrtApi::SessionGetOutputName (37)
  static const int sessionGetOutputName = 37;
  /// OrtApi::SessionGetOverridableInitializerName (38)
  static const int sessionGetOverridableInitializerName = 38;
  /// OrtApi::CreateRunOptions (39)
  static const int createRunOptions = 39;
  /// OrtApi::RunOptionsSetRunLogVerbosityLevel (40)
  static const int runOptionsSetRunLogVerbosityLevel = 40;
  /// OrtApi::RunOptionsSetRunLogSeverityLevel (41)
  static const int runOptionsSetRunLogSeverityLevel = 41;
  /// OrtApi::RunOptionsSetRunTag (42)
  static const int runOptionsSetRunTag = 42;
  /// OrtApi::RunOptionsGetRunLogVerbosityLevel (43)
  static const int runOptionsGetRunLogVerbosityLevel = 43;
  /// OrtApi::RunOptionsGetRunLogSeverityLevel (44)
  static const int runOptionsGetRunLogSeverityLevel = 44;
  /// OrtApi::RunOptionsGetRunTag (45)
  static const int runOptionsGetRunTag = 45;
  /// OrtApi::RunOptionsSetTerminate (46)
  static const int runOptionsSetTerminate = 46;
  /// OrtApi::RunOptionsUnsetTerminate (47)
  static const int runOptionsUnsetTerminate = 47;
  /// OrtApi::CreateTensorAsOrtValue (48)
  static const int createTensorAsOrtValue = 48;
  /// OrtApi::CreateTensorWithDataAsOrtValue (49)
  static const int createTensorWithDataAsOrtValue = 49;
  /// OrtApi::IsTensor (50)
  static const int isTensor = 50;
  /// OrtApi::GetTensorMutableData (51)
  static const int getTensorMutableData = 51;
  /// OrtApi::FillStringTensor (52)
  static const int fillStringTensor = 52;
  /// OrtApi::GetStringTensorDataLength (53)
  static const int getStringTensorDataLength = 53;
  /// OrtApi::GetStringTensorContent (54)
  static const int getStringTensorContent = 54;
  /// OrtApi::CastTypeInfoToTensorInfo (55)
  static const int castTypeInfoToTensorInfo = 55;
  /// OrtApi::GetOnnxTypeFromTypeInfo (56)
  static const int getOnnxTypeFromTypeInfo = 56;
  /// OrtApi::CreateTensorTypeAndShapeInfo (57)
  static const int createTensorTypeAndShapeInfo = 57;
  /// OrtApi::SetTensorElementType (58)
  static const int setTensorElementType = 58;
  /// OrtApi::SetDimensions (59)
  static const int setDimensions = 59;
  /// OrtApi::GetTensorElementType (60)
  static const int getTensorElementType = 60;
  /// OrtApi::GetDimensionsCount (61)
  static const int getDimensionsCount = 61;
  /// OrtApi::GetDimensions (62)
  static const int getDimensions = 62;
  /// OrtApi::GetSymbolicDimensions (63)
  static const int getSymbolicDimensions = 63;
  /// OrtApi::GetTensorShapeElementCount (64)
  static const int getTensorShapeElementCount = 64;
  /// OrtApi::GetTensorTypeAndShape (65)
  static const int getTensorTypeAndShape = 65;
  /// OrtApi::GetTypeInfo (66)
  static const int getTypeInfo = 66;
  /// OrtApi::GetValueType (67)
  static const int getValueType = 67;
  /// OrtApi::CreateMemoryInfo (68)
  static const int createMemoryInfo = 68;
  /// OrtApi::CreateCpuMemoryInfo (69)
  static const int createCpuMemoryInfo = 69;
  /// OrtApi::CompareMemoryInfo (70)
  static const int compareMemoryInfo = 70;
  /// OrtApi::MemoryInfoGetName (71)
  static const int memoryInfoGetName = 71;
  /// OrtApi::MemoryInfoGetId (72)
  static const int memoryInfoGetId = 72;
  /// OrtApi::MemoryInfoGetMemType (73)
  static const int memoryInfoGetMemType = 73;
  /// OrtApi::MemoryInfoGetType (74)
  static const int memoryInfoGetType = 74;
  /// OrtApi::AllocatorAlloc (75)
  static const int allocatorAlloc = 75;
  /// OrtApi::AllocatorFree (76)
  static const int allocatorFree = 76;
  /// OrtApi::AllocatorGetInfo (77)
  static const int allocatorGetInfo = 77;
  /// OrtApi::GetAllocatorWithDefaultOptions (78)
  static const int getAllocatorWithDefaultOptions = 78;
  /// OrtApi::AddFreeDimensionOverride (79)
  static const int addFreeDimensionOverride = 79;
  /// OrtApi::GetValue (80)
  static const int getValue = 80;
  /// OrtApi::GetValueCount (81)
  static const int getValueCount = 81;
  /// OrtApi::CreateValue (82)
  static const int createValue = 82;
  /// OrtApi::CreateOpaqueValue (83)
  static const int createOpaqueValue = 83;
  /// OrtApi::GetOpaqueValue (84)
  static const int getOpaqueValue = 84;
  /// OrtApi::KernelInfoGetAttribute_float (85)
  static const int kernelInfoGetAttribute_float = 85;
  /// OrtApi::KernelInfoGetAttribute_int64 (86)
  static const int kernelInfoGetAttribute_int64 = 86;
  /// OrtApi::KernelInfoGetAttribute_string (87)
  static const int kernelInfoGetAttribute_string = 87;
  /// OrtApi::KernelContext_GetInputCount (88)
  static const int kernelContext_GetInputCount = 88;
  /// OrtApi::KernelContext_GetOutputCount (89)
  static const int kernelContext_GetOutputCount = 89;
  /// OrtApi::KernelContext_GetInput (90)
  static const int kernelContext_GetInput = 90;
  /// OrtApi::KernelContext_GetOutput (91)
  static const int kernelContext_GetOutput = 91;
  /// OrtApi::ReleaseEnv (92)
  static const int releaseEnv = 92;
  /// OrtApi::ReleaseStatus (93)
  static const int releaseStatus = 93;
  /// OrtApi::ReleaseMemoryInfo (94)
  static const int releaseMemoryInfo = 94;
  /// OrtApi::ReleaseSession (95)
  static const int releaseSession = 95;
  /// OrtApi::ReleaseValue (96)
  static const int releaseValue = 96;
  /// OrtApi::ReleaseRunOptions (97)
  static const int releaseRunOptions = 97;
  /// OrtApi::ReleaseTypeInfo (98)
  static const int releaseTypeInfo = 98;
  /// OrtApi::ReleaseTensorTypeAndShapeInfo (99)
  static const int releaseTensorTypeAndShapeInfo = 99;
  /// OrtApi::ReleaseSessionOptions (100)
  static const int releaseSessionOptions = 100;
  /// OrtApi::ReleaseCustomOpDomain (101)
  static const int releaseCustomOpDomain = 101;
  /// OrtApi::GetDenotationFromTypeInfo (102)
  static const int getDenotationFromTypeInfo = 102;
  /// OrtApi::CastTypeInfoToMapTypeInfo (103)
  static const int castTypeInfoToMapTypeInfo = 103;
  /// OrtApi::CastTypeInfoToSequenceTypeInfo (104)
  static const int castTypeInfoToSequenceTypeInfo = 104;
  /// OrtApi::GetMapKeyType (105)
  static const int getMapKeyType = 105;
  /// OrtApi::GetMapValueType (106)
  static const int getMapValueType = 106;
  /// OrtApi::GetSequenceElementType (107)
  static const int getSequenceElementType = 107;
  /// OrtApi::ReleaseMapTypeInfo (108)
  static const int releaseMapTypeInfo = 108;
  /// OrtApi::ReleaseSequenceTypeInfo (109)
  static const int releaseSequenceTypeInfo = 109;
  /// OrtApi::SessionEndProfiling (110)
  static const int sessionEndProfiling = 110;
  /// OrtApi::SessionGetModelMetadata (111)
  static const int sessionGetModelMetadata = 111;
  /// OrtApi::ModelMetadataGetProducerName (112)
  static const int modelMetadataGetProducerName = 112;
  /// OrtApi::ModelMetadataGetGraphName (113)
  static const int modelMetadataGetGraphName = 113;
  /// OrtApi::ModelMetadataGetDomain (114)
  static const int modelMetadataGetDomain = 114;
  /// OrtApi::ModelMetadataGetDescription (115)
  static const int modelMetadataGetDescription = 115;
  /// OrtApi::ModelMetadataLookupCustomMetadataMap (116)
  static const int modelMetadataLookupCustomMetadataMap = 116;
  /// OrtApi::ModelMetadataGetVersion (117)
  static const int modelMetadataGetVersion = 117;
  /// OrtApi::ReleaseModelMetadata (118)
  static const int releaseModelMetadata = 118;
  /// OrtApi::CreateEnvWithGlobalThreadPools (119)
  static const int createEnvWithGlobalThreadPools = 119;
  /// OrtApi::DisablePerSessionThreads (120)
  static const int disablePerSessionThreads = 120;
  /// OrtApi::CreateThreadingOptions (121)
  static const int createThreadingOptions = 121;
  /// OrtApi::ReleaseThreadingOptions (122)
  static const int releaseThreadingOptions = 122;
  /// OrtApi::ModelMetadataGetCustomMetadataMapKeys (123)
  static const int modelMetadataGetCustomMetadataMapKeys = 123;
  /// OrtApi::AddFreeDimensionOverrideByName (124)
  static const int addFreeDimensionOverrideByName = 124;
  /// OrtApi::GetAvailableProviders (125)
  static const int getAvailableProviders = 125;
  /// OrtApi::ReleaseAvailableProviders (126)
  static const int releaseAvailableProviders = 126;
  /// OrtApi::GetStringTensorElementLength (127)
  static const int getStringTensorElementLength = 127;
  /// OrtApi::GetStringTensorElement (128)
  static const int getStringTensorElement = 128;
  /// OrtApi::FillStringTensorElement (129)
  static const int fillStringTensorElement = 129;
  /// OrtApi::AddSessionConfigEntry (130)
  static const int addSessionConfigEntry = 130;
  /// OrtApi::CreateAllocator (131)
  static const int createAllocator = 131;
  /// OrtApi::ReleaseAllocator (132)
  static const int releaseAllocator = 132;
  /// OrtApi::RunWithBinding (133)
  static const int runWithBinding = 133;
  /// OrtApi::CreateIoBinding (134)
  static const int createIoBinding = 134;
  /// OrtApi::ReleaseIoBinding (135)
  static const int releaseIoBinding = 135;
  /// OrtApi::BindInput (136)
  static const int bindInput = 136;
  /// OrtApi::BindOutput (137)
  static const int bindOutput = 137;
  /// OrtApi::BindOutputToDevice (138)
  static const int bindOutputToDevice = 138;
  /// OrtApi::GetBoundOutputNames (139)
  static const int getBoundOutputNames = 139;
  /// OrtApi::GetBoundOutputValues (140)
  static const int getBoundOutputValues = 140;
  /// OrtApi::ClearBoundInputs (141)
  static const int clearBoundInputs = 141;
  /// OrtApi::ClearBoundOutputs (142)
  static const int clearBoundOutputs = 142;
  /// OrtApi::TensorAt (143)
  static const int tensorAt = 143;
  /// OrtApi::CreateAndRegisterAllocator (144)
  static const int createAndRegisterAllocator = 144;
  /// OrtApi::SetLanguageProjection (145)
  static const int setLanguageProjection = 145;
  /// OrtApi::SessionGetProfilingStartTimeNs (146)
  static const int sessionGetProfilingStartTimeNs = 146;
  /// OrtApi::SetGlobalIntraOpNumThreads (147)
  static const int setGlobalIntraOpNumThreads = 147;
  /// OrtApi::SetGlobalInterOpNumThreads (148)
  static const int setGlobalInterOpNumThreads = 148;
  /// OrtApi::SetGlobalSpinControl (149)
  static const int setGlobalSpinControl = 149;
  /// OrtApi::AddInitializer (150)
  static const int addInitializer = 150;
  /// OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools (151)
  static const int createEnvWithCustomLoggerAndGlobalThreadPools = 151;
  /// OrtApi::SessionOptionsAppendExecutionProvider_CUDA (152)
  static const int sessionOptionsAppendExecutionProvider_CUDA = 152;
  /// OrtApi::SessionOptionsAppendExecutionProvider_ROCM (153)
  static const int sessionOptionsAppendExecutionProvider_ROCM = 153;
  /// OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO (154)
  static const int sessionOptionsAppendExecutionProvider_OpenVINO = 154;
  /// OrtApi::SetGlobalDenormalAsZero (155)
  static const int setGlobalDenormalAsZero = 155;
  /// OrtApi::CreateArenaCfg (156)
  static const int createArenaCfg = 156;
  /// OrtApi::ReleaseArenaCfg (157)
  static const int releaseArenaCfg = 157;
  /// OrtApi::ModelMetadataGetGraphDescription (158)
  static const int modelMetadataGetGraphDescription = 158;
  /// OrtApi::SessionOptionsAppendExecutionProvider_TensorRT (159)
  static const int sessionOptionsAppendExecutionProvider_TensorRT = 159;
  /// OrtApi::SetCurrentGpuDeviceId (160)
  static const int setCurrentGpuDeviceId = 160;
  /// OrtApi::GetCurrentGpuDeviceId (161)
  static const int getCurrentGpuDeviceId = 161;
  /// OrtApi::KernelInfoGetAttributeArray_float (162)
  static const int kernelInfoGetAttributeArray_float = 162;
  /// OrtApi::KernelInfoGetAttributeArray_int64 (163)
  static const int kernelInfoGetAttributeArray_int64 = 163;
  /// OrtApi::CreateArenaCfgV2 (164)
  static const int createArenaCfgV2 = 164;
  /// OrtApi::AddRunConfigEntry (165)
  static const int addRunConfigEntry = 165;
  /// OrtApi::CreatePrepackedWeightsContainer (166)
  static const int createPrepackedWeightsContainer = 166;
  /// OrtApi::ReleasePrepackedWeightsContainer (167)
  static const int releasePrepackedWeightsContainer = 167;
  /// OrtApi::CreateSessionWithPrepackedWeightsContainer (168)
  static const int createSessionWithPrepackedWeightsContainer = 168;
  /// OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer (169)
  static const int createSessionFromArrayWithPrepackedWeightsContainer = 169;
  /// OrtApi::SessionOptionsAppendExecutionProvider_TensorRT_V2 (170)
  static const int sessionOptionsAppendExecutionProvider_TensorRT_V2 = 170;
  /// OrtApi::CreateTensorRTProviderOptions (171)
  static const int createTensorRTProviderOptions = 171;
  /// OrtApi::UpdateTensorRTProviderOptions (172)
  static const int updateTensorRTProviderOptions = 172;
  /// OrtApi::GetTensorRTProviderOptionsAsString (173)
  static const int getTensorRTProviderOptionsAsString = 173;
  /// OrtApi::ReleaseTensorRTProviderOptions (174)
  static const int releaseTensorRTProviderOptions = 174;
  /// OrtApi::EnableOrtCustomOps (175)
  static const int enableOrtCustomOps = 175;
  /// OrtApi::RegisterAllocator (176)
  static const int registerAllocator = 176;
  /// OrtApi::UnregisterAllocator (177)
  static const int unregisterAllocator = 177;
  /// OrtApi::IsSparseTensor (178)
  static const int isSparseTensor = 178;
  /// OrtApi::CreateSparseTensorAsOrtValue (179)
  static const int createSparseTensorAsOrtValue = 179;
  /// OrtApi::FillSparseTensorCoo (180)
  static const int fillSparseTensorCoo = 180;
  /// OrtApi::FillSparseTensorCsr (181)
  static const int fillSparseTensorCsr = 181;
  /// OrtApi::FillSparseTensorBlockSparse (182)
  static const int fillSparseTensorBlockSparse = 182;
  /// OrtApi::CreateSparseTensorWithValuesAsOrtValue (183)
  static const int createSparseTensorWithValuesAsOrtValue = 183;
  /// OrtApi::UseCooIndices (184)
  static const int useCooIndices = 184;
  /// OrtApi::UseCsrIndices (185)
  static const int useCsrIndices = 185;
  /// OrtApi::UseBlockSparseIndices (186)
  static const int useBlockSparseIndices = 186;
  /// OrtApi::GetSparseTensorFormat (187)
  static const int getSparseTensorFormat = 187;
  /// OrtApi::GetSparseTensorValuesTypeAndShape (188)
  static const int getSparseTensorValuesTypeAndShape = 188;
  /// OrtApi::GetSparseTensorValues (189)
  static const int getSparseTensorValues = 189;
  /// OrtApi::GetSparseTensorIndicesTypeShape (190)
  static const int getSparseTensorIndicesTypeShape = 190;
  /// OrtApi::GetSparseTensorIndices (191)
  static const int getSparseTensorIndices = 191;
  /// OrtApi::HasValue (192)
  static const int hasValue = 192;
  /// OrtApi::KernelContext_GetGPUComputeStream (193)
  static const int kernelContext_GetGPUComputeStream = 193;
  /// OrtApi::GetTensorMemoryInfo (194)
  static const int getTensorMemoryInfo = 194;
  /// OrtApi::GetExecutionProviderApi (195)
  static const int getExecutionProviderApi = 195;
  /// OrtApi::SessionOptionsSetCustomCreateThreadFn (196)
  static const int sessionOptionsSetCustomCreateThreadFn = 196;
  /// OrtApi::SessionOptionsSetCustomThreadCreationOptions (197)
  static const int sessionOptionsSetCustomThreadCreationOptions = 197;
  /// OrtApi::SessionOptionsSetCustomJoinThreadFn (198)
  static const int sessionOptionsSetCustomJoinThreadFn = 198;
  /// OrtApi::SetGlobalCustomCreateThreadFn (199)
  static const int setGlobalCustomCreateThreadFn = 199;
  /// OrtApi::SetGlobalCustomThreadCreationOptions (200)
  static const int setGlobalCustomThreadCreationOptions = 200;
  /// OrtApi::SetGlobalCustomJoinThreadFn (201)
  static const int setGlobalCustomJoinThreadFn = 201;
  /// OrtApi::SynchronizeBoundInputs (202)
  static const int synchronizeBoundInputs = 202;
  /// OrtApi::SynchronizeBoundOutputs (203)
  static const int synchronizeBoundOutputs = 203;
  /// OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2 (204)
  static const int sessionOptionsAppendExecutionProvider_CUDA_V2 = 204;
  /// OrtApi::CreateCUDAProviderOptions (205)
  static const int createCUDAProviderOptions = 205;
  /// OrtApi::UpdateCUDAProviderOptions (206)
  static const int updateCUDAProviderOptions = 206;
  /// OrtApi::GetCUDAProviderOptionsAsString (207)
  static const int getCUDAProviderOptionsAsString = 207;
  /// OrtApi::ReleaseCUDAProviderOptions (208)
  static const int releaseCUDAProviderOptions = 208;
  /// OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX (209)
  static const int sessionOptionsAppendExecutionProvider_MIGraphX = 209;
  /// OrtApi::AddExternalInitializers (210)
  static const int addExternalInitializers = 210;
  /// OrtApi::CreateOpAttr (211)
  static const int createOpAttr = 211;
  /// OrtApi::ReleaseOpAttr (212)
  static const int releaseOpAttr = 212;
  /// OrtApi::CreateOp (213)
  static const int createOp = 213;
  /// OrtApi::InvokeOp (214)
  static const int invokeOp = 214;
  /// OrtApi::ReleaseOp (215)
  static const int releaseOp = 215;
  /// OrtApi::SessionOptionsAppendExecutionProvider (216)
  static const int sessionOptionsAppendExecutionProvider = 216;
  /// OrtApi::CopyKernelInfo (217)
  static const int copyKernelInfo = 217;
  /// OrtApi::ReleaseKernelInfo (218)
  static const int releaseKernelInfo = 218;
  /// OrtApi::GetTrainingApi (219)
  static const int getTrainingApi = 219;
  /// OrtApi::SessionOptionsAppendExecutionProvider_CANN (220)
  static const int sessionOptionsAppendExecutionProvider_CANN = 220;
  /// OrtApi::CreateCANNProviderOptions (221)
  static const int createCANNProviderOptions = 221;
  /// OrtApi::UpdateCANNProviderOptions (222)
  static const int updateCANNProviderOptions = 222;
  /// OrtApi::GetCANNProviderOptionsAsString (223)
  static const int getCANNProviderOptionsAsString = 223;
  /// OrtApi::ReleaseCANNProviderOptions (224)
  static const int releaseCANNProviderOptions = 224;
  /// OrtApi::MemoryInfoGetDeviceType (225)
  static const int memoryInfoGetDeviceType = 225;
  /// OrtApi::UpdateEnvWithCustomLogLevel (226)
  static const int updateEnvWithCustomLogLevel = 226;
  /// OrtApi::SetGlobalIntraOpThreadAffinity (227)
  static const int setGlobalIntraOpThreadAffinity = 227;
  /// OrtApi::RegisterCustomOpsLibrary_V2 (228)
  static const int registerCustomOpsLibrary_V2 = 228;
  /// OrtApi::RegisterCustomOpsUsingFunction (229)
  static const int registerCustomOpsUsingFunction = 229;
  /// OrtApi::KernelInfo_GetInputCount (230)
  static const int kernelInfo_GetInputCount = 230;
  /// OrtApi::KernelInfo_GetOutputCount (231)
  static const int kernelInfo_GetOutputCount = 231;
  /// OrtApi::KernelInfo_GetInputName (232)
  static const int kernelInfo_GetInputName = 232;
  /// OrtApi::KernelInfo_GetOutputName (233)
  static const int kernelInfo_GetOutputName = 233;
  /// OrtApi::KernelInfo_GetInputTypeInfo (234)
  static const int kernelInfo_GetInputTypeInfo = 234;
  /// OrtApi::KernelInfo_GetOutputTypeInfo (235)
  static const int kernelInfo_GetOutputTypeInfo = 235;
  /// OrtApi::KernelInfoGetAttribute_tensor (236)
  static const int kernelInfoGetAttribute_tensor = 236;
  /// OrtApi::HasSessionConfigEntry (237)
  static const int hasSessionConfigEntry = 237;
  /// OrtApi::GetSessionConfigEntry (238)
  static const int getSessionConfigEntry = 238;
  /// OrtApi::SessionOptionsAppendExecutionProvider_Dnnl (239)
  static const int sessionOptionsAppendExecutionProvider_Dnnl = 239;
  /// OrtApi::CreateDnnlProviderOptions (240)
  static const int createDnnlProviderOptions = 240;
  /// OrtApi::UpdateDnnlProviderOptions (241)
  static const int updateDnnlProviderOptions = 241;
  /// OrtApi::GetDnnlProviderOptionsAsString (242)
  static const int getDnnlProviderOptionsAsString = 242;
  /// OrtApi::ReleaseDnnlProviderOptions (243)
  static const int releaseDnnlProviderOptions = 243;
  /// OrtApi::KernelInfo_GetNodeName (244)
  static const int kernelInfo_GetNodeName = 244;
  /// OrtApi::KernelInfo_GetLogger (245)
  static const int kernelInfo_GetLogger = 245;
  /// OrtApi::KernelContext_GetLogger (246)
  static const int kernelContext_GetLogger = 246;
  /// OrtApi::Logger_LogMessage (247)
  static const int logger_LogMessage = 247;
  /// OrtApi::Logger_GetLoggingSeverityLevel (248)
  static const int logger_GetLoggingSeverityLevel = 248;
  /// OrtApi::KernelInfoGetConstantInput_tensor (249)
  static const int kernelInfoGetConstantInput_tensor = 249;
  /// OrtApi::CastTypeInfoToOptionalTypeInfo (250)
  static const int castTypeInfoToOptionalTypeInfo = 250;
  /// OrtApi::GetOptionalContainedTypeInfo (251)
  static const int getOptionalContainedTypeInfo = 251;
  /// OrtApi::GetResizedStringTensorElementBuffer (252)
  static const int getResizedStringTensorElementBuffer = 252;
  /// OrtApi::KernelContext_GetAllocator (253)
  static const int kernelContext_GetAllocator = 253;
  /// OrtApi::GetBuildInfoString (254)
  static const int getBuildInfoString = 254;
  /// OrtApi::CreateROCMProviderOptions (255)
  static const int createROCMProviderOptions = 255;
  /// OrtApi::UpdateROCMProviderOptions (256)
  static const int updateROCMProviderOptions = 256;
  /// OrtApi::GetROCMProviderOptionsAsString (257)
  static const int getROCMProviderOptionsAsString = 257;
  /// OrtApi::ReleaseROCMProviderOptions (258)
  static const int releaseROCMProviderOptions = 258;
  /// OrtApi::CreateAndRegisterAllocatorV2 (259)
  static const int createAndRegisterAllocatorV2 = 259;
  /// OrtApi::RunAsync (260)
  static const int runAsync = 260;
  /// OrtApi::UpdateTensorRTProviderOptionsWithValue (261)
  static const int updateTensorRTProviderOptionsWithValue = 261;
  /// OrtApi::GetTensorRTProviderOptionsByName (262)
  static const int getTensorRTProviderOptionsByName = 262;
  /// OrtApi::UpdateCUDAProviderOptionsWithValue (263)
  static const int updateCUDAProviderOptionsWithValue = 263;
  /// OrtApi::GetCUDAProviderOptionsByName (264)
  static const int getCUDAProviderOptionsByName = 264;
  /// OrtApi::KernelContext_GetResource (265)
  static const int kernelContext_GetResource = 265;
  /// OrtApi::SetUserLoggingFunction (266)
  static const int setUserLoggingFunction = 266;
  /// OrtApi::ShapeInferContext_GetInputCount (267)
  static const int shapeInferContext_GetInputCount = 267;
  /// OrtApi::ShapeInferContext_GetInputTypeShape (268)
  static const int shapeInferContext_GetInputTypeShape = 268;
  /// OrtApi::ShapeInferContext_GetAttribute (269)
  static const int shapeInferContext_GetAttribute = 269;
  /// OrtApi::ShapeInferContext_SetOutputTypeShape (270)
  static const int shapeInferContext_SetOutputTypeShape = 270;
  /// OrtApi::SetSymbolicDimensions (271)
  static const int setSymbolicDimensions = 271;
  /// OrtApi::ReadOpAttr (272)
  static const int readOpAttr = 272;
  /// OrtApi::SetDeterministicCompute (273)
  static const int setDeterministicCompute = 273;
  /// OrtApi::KernelContext_ParallelFor (274)
  static const int kernelContext_ParallelFor = 274;
  /// OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO_V2 (275)
  static const int sessionOptionsAppendExecutionProvider_OpenVINO_V2 = 275;
  /// OrtApi::SessionOptionsAppendExecutionProvider_VitisAI (276)
  static const int sessionOptionsAppendExecutionProvider_VitisAI = 276;
  /// OrtApi::KernelContext_GetScratchBuffer (277)
  static const int kernelContext_GetScratchBuffer = 277;
  /// OrtApi::KernelInfoGetAllocator (278)
  static const int kernelInfoGetAllocator = 278;
  /// OrtApi::AddExternalInitializersFromFilesInMemory (279)
  static const int addExternalInitializersFromFilesInMemory = 279;
  /// OrtApi::CreateLoraAdapter (280)
  static const int createLoraAdapter = 280;
  /// OrtApi::CreateLoraAdapterFromArray (281)
  static const int createLoraAdapterFromArray = 281;
  /// OrtApi::ReleaseLoraAdapter (282)
  static const int releaseLoraAdapter = 282;
  /// OrtApi::RunOptionsAddActiveLoraAdapter (283)
  static const int runOptionsAddActiveLoraAdapter = 283;
  /// OrtApi::SetEpDynamicOptions (284)
  static const int setEpDynamicOptions = 284;
  /// OrtApi::ReleaseValueInfo (285)
  static const int releaseValueInfo = 285;
  /// OrtApi::ReleaseNode (286)
  static const int releaseNode = 286;
  /// OrtApi::ReleaseGraph (287)
  static const int releaseGraph = 287;
  /// OrtApi::ReleaseModel (288)
  static const int releaseModel = 288;
  /// OrtApi::GetValueInfoName (289)
  static const int getValueInfoName = 289;
  /// OrtApi::GetValueInfoTypeInfo (290)
  static const int getValueInfoTypeInfo = 290;
  /// OrtApi::GetModelEditorApi (291)
  static const int getModelEditorApi = 291;
  /// OrtApi::CreateTensorWithDataAndDeleterAsOrtValue (292)
  static const int createTensorWithDataAndDeleterAsOrtValue = 292;
  /// OrtApi::SessionOptionsSetLoadCancellationFlag (293)
  static const int sessionOptionsSetLoadCancellationFlag = 293;
  /// OrtApi::GetCompileApi (294)
  static const int getCompileApi = 294;
  /// OrtApi::CreateKeyValuePairs (295)
  static const int createKeyValuePairs = 295;
  /// OrtApi::AddKeyValuePair (296)
  static const int addKeyValuePair = 296;
  /// OrtApi::GetKeyValue (297)
  static const int getKeyValue = 297;
  /// OrtApi::GetKeyValuePairs (298)
  static const int getKeyValuePairs = 298;
  /// OrtApi::RemoveKeyValuePair (299)
  static const int removeKeyValuePair = 299;
  /// OrtApi::ReleaseKeyValuePairs (300)
  static const int releaseKeyValuePairs = 300;
  /// OrtApi::RegisterExecutionProviderLibrary (301)
  static const int registerExecutionProviderLibrary = 301;
  /// OrtApi::UnregisterExecutionProviderLibrary (302)
  static const int unregisterExecutionProviderLibrary = 302;
  /// OrtApi::GetEpDevices (303)
  static const int getEpDevices = 303;
  /// OrtApi::SessionOptionsAppendExecutionProvider_V2 (304)
  static const int sessionOptionsAppendExecutionProvider_V2 = 304;
  /// OrtApi::SessionOptionsSetEpSelectionPolicy (305)
  static const int sessionOptionsSetEpSelectionPolicy = 305;
  /// OrtApi::SessionOptionsSetEpSelectionPolicyDelegate (306)
  static const int sessionOptionsSetEpSelectionPolicyDelegate = 306;
  /// OrtApi::HardwareDevice_Type (307)
  static const int hardwareDevice_Type = 307;
  /// OrtApi::HardwareDevice_VendorId (308)
  static const int hardwareDevice_VendorId = 308;
  /// OrtApi::HardwareDevice_Vendor (309)
  static const int hardwareDevice_Vendor = 309;
  /// OrtApi::HardwareDevice_DeviceId (310)
  static const int hardwareDevice_DeviceId = 310;
  /// OrtApi::HardwareDevice_Metadata (311)
  static const int hardwareDevice_Metadata = 311;
  /// OrtApi::EpDevice_EpName (312)
  static const int epDevice_EpName = 312;
  /// OrtApi::EpDevice_EpVendor (313)
  static const int epDevice_EpVendor = 313;
  /// OrtApi::EpDevice_EpMetadata (314)
  static const int epDevice_EpMetadata = 314;
  /// OrtApi::EpDevice_EpOptions (315)
  static const int epDevice_EpOptions = 315;
  /// OrtApi::EpDevice_Device (316)
  static const int epDevice_Device = 316;
  /// OrtApi::GetEpApi (317)
  static const int getEpApi = 317;
}
